# Generated by Django 3.2.7 on 2021-10-06 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishmessage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 6, 8, 25, 58, 406687, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishmessage',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
