version: '3'
    
services:

  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123qwe
    volumes:
      - "./postgres:/var/lib/postgresql/data"


 # to run with runserver use the line below instead of gunicorn blog.wsgi ...
 # python manage.py runserver 0.0.0.0:8000    
 # gunicorn blog.wsgi:application # run wsgi via gunicorn
  web:
    build: ./blog
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn blog.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DB_NAME=blog
      - DB_USER=postgres
      - DB_PASSWORD=123qwe
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./blog:/blog
    ports:
      - "8000:8000"
    depends_on:
      - db
