# Generated by Django 3.2.7 on 2021-10-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('allow_mailing', models.BooleanField(default=False)),
            ],
        ),
    ]
